from infrastructure.kafka_clients import BaseKafkaClient


class KafkaAdmin(BaseKafkaClient):

    def __init__(self):
        pass

    async def start(self): ...

    async def stop(self): ...

    async def health_check(self): ...

    async def create_topic(self): ...

    async def delete_topic(self): ...

    async def list_topics(self): ...

    async def additional_partitions_for_topic(self): ...
        #create_partitions
